### ISSUE TITLE
Enchancement

### ISSUE THREAD

**Issue by iGetUploaded** [Rdimo/Hazard-Nuker#1]
Would like to see it be able to leave servers made by the user(incase of being hacked and created mass servers)

**Comment by Rdimo** [comment]
there already is an option to leave servers, which you can just choose [3] delete and leave all servers and put in your main token and it will delete all the servers that you have. although this will not work if you have 2fa enabled since Hazard nuker would need the verification code to be able to delete the server so best thing would be to disable it then delete all the servers and then enable it back on again. Hope that helps :D
