### ISSUE TITLE
Hazard Nuker [HELP] driver issues

### ISSUE THREAD

**Issue by mudkipzlover1** [Rdimo/Hazard-Nuker#186]
Driver not found! Installing it for you
Traceback (most recent call last):
  File "/home/mudkip/Hazard-Nuker/Hazard.py", line 531, in <module>
    main()
  File "/home/mudkip/Hazard-Nuker/Hazard.py", line 331, in main
    util.QR_Grabber.QR_Grabber(WebHook)
  File "/home/mudkip/Hazard-Nuker/util/QR_Grabber.py", line 40, in QR_Grabber
    type_ = getDriver()
  File "/home/mudkip/Hazard-Nuker/util/plugins/common.py", line 250, in getDriver
    if os.path.exists(os.getenv('localappdata') + '\\Google'):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

this appears when im trying to do qr code 

arch linux, XCFE desktop, nvidia

**Comment by RandomVersion** [comment]
bro qr isnt for linux

**Comment by dekrypted** [comment]
"Linux Support! (Expect Bugs)" s/o README.md

Linux does not have the environment variables/file system that Windows does. If you really need to use the QR Logger, use a Virtual Machine (VirtualBox and QEMU are two good options. VirtualBox is more user-friendly and QEMU is more lightweight)

Let me know if you need any more assistance, otherwise please close this ticket.

Thank you!
- DeKrypt

**Comment by RAZIMARAI** [comment]
12

**Comment by RandomVersion** [comment]
btw the issue is beacuse hz used ms edge and since linux dosn't support ms edge it wont work, and also bc of the driver

**Comment by mudkipzlover1** [comment]
fuck alright thanks guys
