### ISSUE TITLE
Free Malware 

### ISSUE THREAD

**Issue by Eddippla** [Rdimo/Hazard-Nuker#2]
Thanks!

**Comment by COD1EINE** [comment]
Proof that it's malware?

**Comment by Rdimo** [comment]
Hazard Nuker is not a malware, if your concerned about the fact that it's not open source is simply because I spent day in and day out making this tool and just want to keep the credits, dont want some kid to just skid it in 2 seconds while it took me months to make it, I have no malware implemented into Hazard and if you still are concerned contact me and I can show you the whole source to it, aditionally explaining what everything does etc

**Comment by AnimeWife** [comment]
+rep
