### ISSUE TITLE
isnt this illegal?

### ISSUE THREAD

**Issue by AnonimFan** [Rdimo/Hazard-Nuker#45]
**Type your question here**
Like it gets the targeted accounts city? you could visit the human there, do things i dont even want to know

from my view, it is illegal

**Comment by Rdimo** [comment]
alr
1. couldn't care less
2. can't even go to jail
3. I've done things that's 100x worse than this measly program 
4. the location is not exact but can be kinda accurate
5. if you think this is illegal and don't want to take a part of it then simply **don't** 
6. it's for educational purposes too ofc

**Comment by Rdimo** [comment]
and if you want to complain to someone

**Comment by windows-fryer** [comment]
I love the fact that you hide under the fact that you're aliasing on a website. Admitting that you've done something worse than a [felony](https://www.law.cornell.edu/uscode/text/18/1029) is sad. Let the harsh reality set in that you'll be rotting in a cell within 5 years time.

**Comment by IgnHeaven** [comment]
#emo

**Comment by Rdimo** [comment]
> I love the fact that you hide under the fact that you're aliasing on a website. Admitting that you've done something worse than a [felony](https://www.law.cornell.edu/uscode/text/18/1029) is sad. Let the harsh reality set in that you'll be rotting in a cell within 5 years time.

bro, xd first of all I don't live in the us so the link you sent doesn't effect for me, the laws here are way different and I can't even go to jail. literally couldn't care less that I've done things worse than coding a program and what you people do with it is not my responebility so by your logic 2k+ people should be sent to jail. I code things for fun and the fact that your even here just proves that your intrested in malicious stuff or you just decide to interfere and argument because your just a 14 year old kid which explain alot by itself. Join my [discord](https://rdimo.github.io/CheatAway/) ping me so we can vc, love to talk with unintelligent people like you and learn them how this sad world really works

**Comment by AnonimFan** [comment]
What do you even mean by "couldn't care less"?

**Comment by Rdimo** [comment]
means that I couldn't care less, if you understand english you should have no issue figuring out what that means, take your time tho if you need a moment to think about what it means

**Comment by AnonimFan** [comment]
Alright, i am hungaraian not an English person so saying "if you understand english" are a spacefiller and useless words

**Comment by Rdimo** [comment]
what? doesn't even matter if it's useless words, it was a question xD  suppose if you say that you mean that you don't understand english and didn't even answer the question which just proves my point yet again

**Comment by AnonimFan** [comment]
last question: what country do you live in?

**Comment by Rdimo** [comment]
Sweden
