### ISSUE TITLE
Image grabber bugged

### ISSUE THREAD

**Issue by ppfart69420** [Rdimo/Hazard-Nuker#9]
On the newest version as of now 1.2.7 if you try the image grabber it installs the chrome driver then it crashes and gives some error.

**Comment by ppfart69420** [comment]
on older versions it works

**Comment by Rdimo** [comment]
by image grabber I suppose you mean qr code grabber? the reason why it crashes could be because it's the wrong driver and you may need to install one manually but if it worked before that shouldn't be the case, the latest version is 1.2.8 and 1.2.9 coming out soon, could you contact me and send me the error? :)

**Comment by Rdimo** [comment]
actually there is a update with regarding a module which lead to that

**Comment by ppfart69420** [comment]
ok thanks
